### ISSUE TITLE
Неправильно устанавливается имя для .ipa-файла.

### ISSUE THREAD

**Issue by atom-wintermute** [rambler-ios/fastlane-flows#11]
:XCODEBUILD_ARCHIVE=>"/Users/jenkins/Library/Developer/Xcode/Archives/2016-11-01/Restaurants 2016-11-01 17.31.24.xcarchive"}
ERROR [2016-11-01 17:34:38.83]: Couldn't find ipa file at path 'Release.ipa'

судя по всему fastlane пытается найти файл по названию схемы, но такого нет

**Comment by CognitiveDisson** [comment]
Исправил, указав явно имя ipa файла в команде gym равному имени схемы.
